apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-pvc
spec:
  selector:
    matchLabels:
      app: deployment-nginx-pvc
  replicas: 1
  template:
    metadata:
      annotations:
        scheduling.k8s.io/group-name: pg-deployment-nginx-pvc
      labels:
        app: deployment-nginx-pvc
    spec:
      schedulerName: kube-batch
      terminationGracePeriodSeconds: 1
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '100m'
              memory: 100Mi
            limits:
              cpu: '100m'
              memory: 100Mi
          volumeMounts:
            - mountPath: /mnt/claim
              name: local-vol
      volumes:
        - name: local-vol
          persistentVolumeClaim:
            claimName: claim-deployment-nginx-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-deployment-nginx-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
---
apiVersion: scheduling.incubator.k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: pg-deployment-nginx-pvc
spec:
  minMember: 1
  queue: default
