apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-with-shadow-pg
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        scheduling.k8s.io/shadow-pod-group: shadow-pg
    spec: 
      schedulerName: kube-batch
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
      nodeSelector:
        host.type: real

