apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-with-volcano
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        #create test queue and use this annotation
        #to make deployment be scheduled into test queue
        #scheduling.volcano.sh/queue-name: test
        # need podgroup, otherwise it will use default pg with min member 1
        scheduling.k8s.io/group-name: deploy-with-volcano-pg
    spec:
      # set spec.schedulerName to 'volcano' instead of
      # 'default-scheduler' for deployment.
      schedulerName: volcano
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
              memory: 100Mi
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  name: deploy-with-volcano-pg
  namespace: default
spec:
  minMember: 2
  queue: default
