apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: queue-b
spec:
  reclaimable: true
  weight: 1
  guarantee:
    resource:
      cpu: 2
      memory: 1Gi
  deserved:
    cpu: 4
    memory: 2Gi
  capability:          
    cpu: 4
    memory: 2Gi
