apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-job-
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  parallelism: 3
  completions: 3
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
        args: ["30s"]
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
      restartPolicy: Never

---
# kubectl patch job/myjob --type=strategic --patch '{"spec":{"suspend":false}}'
apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  suspend: true
  parallelism: 1
  completions: 5
  template:
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['/bin/sh']
          args: ['-c', 'sleep 30']
          resources:
            requests:
              cpu: '100m'
              memory: 100Mi
      restartPolicy: Never