apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-low
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-low
  template:
    metadata:
      labels:
        app: deployment-low
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: "1000m"
            memory: 100Mi
          requests:
            cpu: "1000m"
            memory: 100Mi
        lifecycle:
            preStop:
              exec:
                # command: ["/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done"]
                command: ["/bin/sh", "-c", "sleep 20s"]
      priorityClassName: low-priority
      terminationGracePeriodSeconds: 30
