apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-short
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-short
  template:
    metadata:
      labels:
        app: deployment-short
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: "2000m"
            memory: 100Mi
          requests:
            cpu: "2000m"
            memory: 100Mi
        lifecycle:
            # postStart:
            #   exec:
            #     command: ["/bin/sh", "-c", "echo Hello from the postStart handler"]
            preStop:
              exec:
                # command: ["/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done"]
                command: ["/bin/sh", "-c", "sleep 5s"]
      priorityClassName: low-priority
      terminationGracePeriodSeconds: 10
