apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-batch-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-batch-sa-admin
subjects:
  - kind: ServiceAccount
    name: kube-batch-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
