apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-batch-scheduler-conf
  namespace: kube-system
data:
  kube-batch-scheduler-conf.yaml: |
    actions: "enqueue, allocate, preempt, reclaim"
    tiers:
    - plugins:
        - name: priority
        - name: gang
        - name: conformance
        - name: resource-queue
          arguments:
            enabledStrategyList: mostGPUFirst,leastPriorityFirst
        - name: elastic
        - name: drf
        - name: hybrid
        - name: proportion
    - plugins:
        - name: predicates
          arguments:
            predicate.MemoryPressureEnable: true
            predicate.DiskPressureEnable: true
            predicate.PIDPressureEnable: true
            predicate.TencentVGPUEnable: true
        - name: task-topology
          arguments:
            task-topology.weight: 10
        - name: nodeorder
          arguments:
            balancedresource.weight: 3
            leastrequested.weight: 1
            mostrequested.weight: 2
        - name: network-aware
          arguments:
            networkTopologyAware.weight: 10
        - name: load-aware
          arguments:
            loadAware.weight: 5
    configurations:
        - name: enqueue
          arguments:
            enqueue.policy: 0
        - name: allocate
          arguments:
            forbid.others.waiting.hours: 24
        - name: reclaim
          arguments:
            reclaim.policy: 2
        - name: load-aware
          arguments:
            shortTerm: 5m
            longTerm: 30m
    feasibleConf:
        minNodesToFind: 100
        percentageOfNodesToFind: 10
        minPercentageOfNodesToFind: 10
