apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job5
spec:
  schedulerName: volcano
  queue: queue-a #test-overuse
  tasks:
    - replicas: 2
      name: "master"
      template:
        metadata:
          annotations:
            scheduling.k8s.io/group-name: vcjob-1
            volcano.sh/preemptable: true
        spec:
          containers:
            - image: nginx
              name: nginx
              resources:
                requests:
                  cpu: "500m"
                  memory: "50Mi"
          restartPolicy: OnFailure
    - replicas: 2
      minAvailable: 1
      name: "work"
      template:
        metadata:
          annotations:
            scheduling.k8s.io/group-name: vcjob-1
            volcano.sh/preemptable: true
        spec:
          containers:
            - image: nginx
              name: nginx
              resources:
                requests:
                  cpu: "500m"
                  memory: "100Mi"
          restartPolicy: OnFailure
