apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ['xxx', '-c', 'echo "Hello"']
      restartPolicy: Never
