apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ['/bin/sh', '-c', 'echo "Hello"']
        resources:
          requests:
            cpu: "10"
      restartPolicy: Never
